project:
  type: book
  output-dir: docs

book:
  title: "Quarto Based OTTR Course"
  author: "Howard Baek"
  date: "4/3/2024"
  favicon: favicon.ico
  page-navigation: true
  search: true
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar: 
    search: true
  
  page-footer:
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a> by 
      The Fred Hutch Data Science Lab
    center: |
      All illustrations <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY. </a>
      <br>
      All other materials <a href= "https://creativecommons.org/licenses/by/4.0/"> CC-BY </a> unless noted otherwise.
    right: |
     Please provide feedback <a href= "https://docs.google.com/forms/d/e/1FAIpQLSfBvVELBg8lcynKj0TrzMlov1zil-Sbkh9VhMKRcSpeo1xo6g/viewform"> here </a>

bibliography: references.bib

format:
  html:
    css: style.css
knitr:
  opts_chunk:
    fig.path: "resources/images/figure/"


    