project:
  type: book
  output-dir: docs

book:
  title: "Quarto Based OTTR Course"
  author: "Howard Baek"
  date: "4/3/2024"
  favicon: img/favicon.ico

  page-navigation: true
  search: true
  repo-url: https://github.com/fhdsl/ottr
  repo-actions: [edit] 
  issue-url: https://github.com/fhdsl/ottr/issues
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: "First Section"
      chapters:
        - first-section-new-chapter.qmd
    - part: "Second Section"
      chapters:
        - second-section-new-chapter.qmd
    - part: "Third Section"
      chapters:
        - third-section-new-chapter.qmd
    - conclusion.qmd
    - references.qmd
    
  navbar:
    title: false
    background: white
    foreground: black
    logo: /img/logo.jpeg
    logo-href: https://hutchdatascience.org
    search: true
  
  page-footer:
    left: |
      This book was built with <a href="https://quarto.org/" style="color: #fff;">Quarto</a> by 
      <a href="https://hutchdatascience.org/" style="color: #fff;">The Fred Hutch Data Science Lab</a>.
    center: |
      All illustrations <a href="https://creativecommons.org/licenses/by/4.0/" style="color: #fff;">CC-BY. </a>
      <br>
      All other materials <a href= "https://creativecommons.org/licenses/by/4.0/" style="color: #fff;"> CC-BY </a> unless noted otherwise.
    right: |
     Please take a moment to share your feedback with us by filling out this 
     <a href= "https://docs.google.com/forms/d/e/1FAIpQLSfBvVELBg8lcynKj0TrzMlov1zil-Sbkh9VhMKRcSpeo1xo6g/viewform" style="color: #fff;"> Google Form </a>.

bibliography: references.bib

format:
  html:
    css: style.css
    code-link: true
    link-external-newwindow: true
    linkcolor: "#00C1D5"
    image: img/favicon.ico
knitr:
  opts_chunk:
    fig.path: "resources/images/figure/"



    