name: Clean Docs and No TOC Directory

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  clean-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Delete files in docs/no_toc
        run: |
          find docs/no_toc -mindepth 1 -delete

      - name: Delete other files in docs
        run: |
          find docs -mindepth 1 ! -path 'docs/no_toc*' -delete

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Cleaned up docs directory" || echo "No changes to commit"
          git push
